# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from config.config import launch_name


class Ui_RegWind:
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.setFixedSize(800, 600)
    def setup_registration_window(self):

        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 30, 481, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line1_email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line1_email.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.line1_email)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line1_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line1_name.setObjectName("line1_name")
        self.verticalLayout.addWidget(self.line1_name)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line1_password1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line1_password1.setObjectName("line1_password1")
        self.verticalLayout.addWidget(self.line1_password1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line1_password1_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line1_password1_2.setObjectName("line1_password1_2")
        self.verticalLayout.addWidget(self.line1_password1_2)
        self.but1_send = QtWidgets.QPushButton(self.centralwidget)
        self.but1_send.setGeometry(QtCore.QRect(508, 304, 141, 51))
        self.but1_send.setObjectName("but1_send")
        self.but1_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.but1_cancel.setGeometry(QtCore.QRect(150, 300, 141, 51))
        self.but1_cancel.setObjectName("but1_cancel")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(310, 400, 301, 71))
        self.label_error.setObjectName("label_error")
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)
        self.label_error.close()
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("RegWind", launch_name))
        self.label_4.setText(_translate("RegWind", "Почта"))
        self.label.setText(_translate("RegWind", "Имя пользователя"))
        self.label_2.setText(_translate("RegWind", "Пароль"))
        self.label_3.setText(_translate("RegWind", "Пароль"))
        self.but1_send.setText(_translate("RegWind", "Отправить"))
        self.but1_cancel.setText(_translate("RegWind", "Назад"))
        self.label_error.setText(_translate("RegWind", ""))

    def get_data_for_registration(self):
        return {
            "email": self.line1_email.text(),
            "username": self.line1_name.text(),
            "password1": self.line1_password1.text(),
            "password2": self.line1_password1_2.text()
        }

    def registration_error(self, error):
        print(error)
        self.label_error.setText(error)
        self.label_error.show()

